#!/bin/sh /etc/rc.common

START=10
STOP=15

BOINCEXE_NAME=boinc_client
BOINCDIR=/opt/boinc/

start() {
   PID=$( pidof $BOINCEXE_NAME )
   if ! [ -z "$PID" ]; then
      echo "ERROR: Another instance of BOINC is running PID=${PID}"
      return 2
   fi

   if ! [ -d "$BOINCDIR" ]; then
      echo -n "Creating $BOINCDIR..."
      if mkdir -p $BOINCDIR 2>/dev/null ; then
         echo "[OK]"
      else
         echo "[FAILED]"
         return 1
      fi
   fi


   cd $BOINCDIR
   echo "Starting Boinc-client..."
   ${BOINCEXE_NAME} 2>/dev/null > /dev/null &

   return 0
}

stop() {
   PID=$( pidof $BOINCEXE_NAME )
   if ! [ -z "$PID" ]; then
      kill $PID
      echo -n "I: Stopping BOINC with PID $PID... "
      sleep 10

      PID=$( pidof $BOINCEXE_NAME )
      if ! [ -z "$PID" ]; then
	 echo " [FAILED]"
         return 1;
      fi
      echo " [OK]"
      return 0;
   else
      echo "I: Boinc was not running."
      return 0
   fi
}

restart() {
   if stop ; then
      start
   else
      echo "E: BOINC could not be stopped."
   fi
}

