#!/bin/sh /etc/rc.common

START=99
STOP=0

BOINCEXE_NAME=boinc_client
BOINCDIR=/opt/boinc/
BOINCUSR=boinc
BOINCEXE_OPTS="--check_all_logins --redirectio --dir $BOINCDIR"

start() {
   PID=$( pidof $BOINCEXE_NAME )
   if ! [ -z "$PID" ]; then
      echo "ERROR: Another instance of BOINC is running PID=${PID}"
      return 2
   fi

   if ! [ -d "$BOINCDIR" ]; then
      echo -n "Creating $BOINCDIR... "
      if ! mkdir -p $BOINCDIR 2>/dev/null ; then
         echo "[FAILED]"
         return 1
      fi
      echo "[OK]"
   fi

   echo -n "Checking ownership of $BOINCDIR... "
   BOINCDIR_OWNER="$(ls -ld $BOINCDIR | awk '{print $3}')"
   if [ "$BOINCUSR" != "$BOINCDIR_OWNER" ] ; then
      echo -n "(fixing)... "
      chown -R $BOINCUSR:$BOINCUSR $BOINCDIR
      BOINCDIR_OWNER="$(ls -ld $BOINCDIR | awk '{print $3}')"
      if [ "$BOINCUSR" != "$BOINCDIR_OWNER" ] ; then
         echo "[FAILED] ('$BOINCUSR' != '$BOINCDIR_OWNER')"
         return 3
      fi
   fi
   echo "[OK]"

   cd $BOINCDIR
   echo -n "Starting Boinc-client... "
   start-stop-daemon -S -q -b -c $BOINCUSR:$BOINCUSR \
                     -x $BOINCEXE_NAME -- $BOINCEXE_OPTS

   PID=$( pidof $BOINCEXE_NAME )
   if [ -z "$PID" ]; then
      echo "[FAILED]"
      return 4
   fi
   echo "[OK]"
}

stop() {
   PID=$( pidof $BOINCEXE_NAME )
   if ! [ -z "$PID" ]; then
      start-stop-daemon -K -q -x $BOINCEXE_NAME

      echo -n "Stopping BOINC... "
      sleep 10

      PID=$( pidof $BOINCEXE_NAME )
      if ! [ -z "$PID" ]; then
	 echo "[FAILED]"
         return 1;
      fi
      echo "[OK]"
   else
      echo "[was not running]"
    fi
    return 0
}

restart() {
   if stop ; then
      start
   else
      echo "E: BOINC could not be stopped."
   fi
}

